server:
  port: 8088
spring:
  datasource:
      url: jdbc:mysql://119.45.23.62:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
      password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl